import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { MessageSquare, TrendingUp, Users, Signal, Brain, GraduationCap } from 'lucide-react';
import CreatePostDialog from './CreatePostDialog';
import EnhancedPostCard from './EnhancedPostCard';
var CommunityFeed = function (_a) {
    var activeTab = _a.activeTab, posts = _a.posts, onToggleLike = _a.onToggleLike, onCreatePost = _a.onCreatePost;
    var renderFeedContent = function () {
        switch (activeTab) {
            case 'feed':
                return (_jsx("div", { className: "w-full", children: _jsxs("div", { className: "space-y-3", children: [_jsxs("div", { className: "hidden lg:flex items-center justify-between", children: [_jsx("h2", { className: "text-xl font-semibold text-off-white", children: "Following Feed" }), _jsx(CreatePostDialog, { onCreatePost: onCreatePost })] }), _jsx("div", { className: "space-y-3 pb-20 lg:pb-4", children: posts.length === 0 ? (_jsxs("div", { className: "text-center text-off-white/60 py-12 px-4", children: [_jsx(MessageSquare, { className: "w-12 h-12 mx-auto mb-4 opacity-50" }), _jsx("p", { children: "No posts from people you follow yet." }), _jsx("p", { className: "text-sm mt-2", children: "Follow some traders to see their content here!" })] })) : (posts.map(function (post) { return (_jsx(EnhancedPostCard, { post: post, onToggleLike: onToggleLike }, post.id)); })) })] }) }));
            case 'trending':
                return (_jsx("div", { className: "w-full", children: _jsxs("div", { className: "space-y-6 pb-20 lg:pb-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(TrendingUp, { className: "w-6 h-6 text-secondary" }), _jsx("h2", { className: "text-xl font-semibold text-off-white", children: "Trending Now" })] }), _jsx("div", { className: "space-y-4", children: _jsxs("div", { className: "glass-card", children: [_jsx("h3", { className: "font-semibold text-off-white mb-3", children: "\uD83D\uDD25 Hot Topics" }), _jsx("div", { className: "space-y-3", children: ['$KCB earnings surprise', '$EABL dividend announcement', 'NSE IPO pipeline', 'Forex volatility'].map(function (topic, i) { return (_jsxs("div", { className: "flex items-center justify-between p-3 bg-white/5 rounded-lg", children: [_jsx("span", { className: "text-off-white", children: topic }), _jsxs("span", { className: "text-secondary text-sm", children: ["#", i + 1] })] }, i)); }) })] }) })] }) }));
            case 'discussions':
                return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Users, { className: "w-6 h-6 text-secondary" }), _jsx("h2", { className: "text-xl font-semibold text-off-white", children: "Active Discussions" })] }), _jsx("div", { className: "pb-20 lg:pb-4", children: _jsxs("div", { className: "text-center text-off-white/60 py-12", children: [_jsx(Users, { className: "w-12 h-12 mx-auto mb-4 opacity-50" }), _jsx("p", { children: "Discussion forums coming soon!" }), _jsx("p", { className: "text-sm mt-2", children: "Engage in structured trading discussions" })] }) })] }));
            case 'signals':
                return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Signal, { className: "w-6 h-6 text-secondary" }), _jsx("h2", { className: "text-xl font-semibold text-off-white", children: "Trading Signals" })] }), _jsx("div", { className: "pb-20 lg:pb-4", children: _jsxs("div", { className: "text-center text-off-white/60 py-12", children: [_jsx(Signal, { className: "w-12 h-12 mx-auto mb-4 opacity-50" }), _jsx("p", { children: "Trading signals feature coming soon!" }), _jsx("p", { className: "text-sm mt-2", children: "Get verified trading signals from experts" })] }) })] }));
            case 'ai-insights':
                return (_jsx("div", { className: "w-full", children: _jsxs("div", { className: "space-y-6 pb-20 lg:pb-4", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(Brain, { className: "w-6 h-6 text-secondary" }), _jsx("h2", { className: "text-xl font-semibold text-off-white", children: "AI Market Insights" })] }), _jsxs("div", { className: "glass-card", children: [_jsx("h3", { className: "font-semibold text-off-white mb-3", children: "\uD83E\uDD16 Invisa Daily Summary" }), _jsxs("div", { className: "space-y-4", children: [_jsxs("div", { className: "p-4 bg-secondary/10 rounded-lg border border-secondary/20", children: [_jsxs("p", { className: "text-off-white mb-2", children: [_jsx("strong", { children: "Market Sentiment:" }), " Bullish"] }), _jsx("p", { className: "text-off-white/80 text-sm", children: "Most traders are optimistic about $KCB and $EABL based on recent discussions." })] }), _jsxs("div", { className: "p-4 bg-blue-500/10 rounded-lg border border-blue-500/20", children: [_jsx("p", { className: "text-off-white mb-2", children: _jsx("strong", { children: "Top Discussions:" }) }), _jsxs("p", { className: "text-off-white/80 text-sm", children: ["1. Earnings season expectations", _jsx("br", {}), "2. Currency hedge strategies", _jsx("br", {}), "3. Tech stock valuations"] })] })] })] })] }) }));
            case 'mentorship':
                return (_jsxs("div", { className: "space-y-6", children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsx(GraduationCap, { className: "w-6 h-6 text-secondary" }), _jsx("h2", { className: "text-xl font-semibold text-off-white", children: "Mentorship Hub" })] }), _jsx("div", { className: "pb-20 lg:pb-4", children: _jsxs("div", { className: "text-center text-off-white/60 py-12", children: [_jsx(GraduationCap, { className: "w-12 h-12 mx-auto mb-4 opacity-50" }), _jsx("p", { children: "Mentorship program coming soon!" }), _jsx("p", { className: "text-sm mt-2", children: "Connect with experienced traders for guidance" })] }) })] }));
            default:
                return renderFeedContent();
        }
    };
    return (_jsx("div", { className: "w-full", children: renderFeedContent() }));
};
export default CommunityFeed;
